### ISSUE TITLE
VM Desktop Icons

### ISSUE THREAD

**Issue by WetGeek** [getsolus/budgie-desktop-view#10]

**Comment by WetGeek** [comment]
The recent update changed the means of creating desktop icons in a way that is transparent to users at the keyboard, but not to VirtualBox.  It is no longer able to create icons that represent existing VMs.  Selecting that option from the VBox manager's context menu quietly does nothing.  Using Budgie DE.  Another way to create such icons is needed, since the original method no longer works.

**Comment by JoshStrobl** [comment]
> Selecting that option from the VBox manager's context menu quietly does nothing.

This seems more like a bug in VirtualBox Manager then? The context menu _should_ just generate a desktop file and place it in `~/Desktop`, whether or not it actually does that is entirely another question. Like it shouldn't have been tying into Nautilus at all, as an example, and even if it did it shouldn't have been nautilus' desktop icons either.

An audit of VirtualBox sounds necessary.

**Comment by JoshStrobl** [comment]
Closing since apparently they just had icons disabled :D
