### ISSUE TITLE
desktop icons disappear: segfault

### ISSUE THREAD

**Issue by splace** [getsolus/budgie-desktop-view#11]
```
[[25288.647580] us.getsol.budgi[1117]: segfault at 0 ip 00007f34c5ea8090 sp 00007ffe936d58e8 error 4 in libglib-2.0.so.0.6600.3[7f34c5e84000+86000]
[25288.647591] Code: c4 08 48 89 f8 5b 5d c3 66 90 48 83 ec 08 e8 07 c6 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 2e 0f 1f 84 00 00 00 00 00 <0f> be 07 41 b8 05 15 00 00 84 c0 74 19 0f 1f 00 44 89 c2 48 83 c7]
```

happening, reliably,  either on login or a few hours after login/boot.

all up to date, system files checked, no changes to files in desktop dir.

no issues before change to desk-top-view.

**Comment by JoshStrobl** [comment]
Could you do the following for me so I can get a more comprehensive backlog?

1. Run the following command to install the debugger and necessary dbginfo package:  `sudo eopkg install gdb budgie-desktop-view-dbginfo`
2. Make sure there is no `us.getsol.budgie-desktop-view` running by running `killall -9 us.getsol.budgie-desktop-view`
3. Open up a terminal and run: `gdb us.getsol.budgie-desktop-view 2&>1 | tee ~/budgie-desktop-view-gdb.txt`
4. Keep the terminal going in the background. When budgie-desktop-view crashes, switch to the terminal and do: `backtrace full`
5. After this, type `quit` and `gdb` will exit.
6. Upload the txt file here.

Thanks!

**Comment by tauchvogel** [comment]
I am using Budgie desktop. I have the same issues. I try to do the way, Josh has explained.

**Comment by JoshStrobl** [comment]
Any update on getting me the backtrace for this?

**Comment by tauchvogel** [comment]
I tried to do the command "gdb us.getsol.budgie-desktop-view 2&>1 | tee ~/budgie-desktop-view-gdb.txt" and r as in run.  After that I only saw the cursor blinking in the terminal. Nothing else happened. How long does this command work to do the textfile?

**Comment by JoshStrobl** [comment]
> How long does this command work to do the textfile?
> I tried again. But maybe something went wrong or I hade done the wrong workout in the terminal. The textfile is empty.

Unless it segfaults, you run the backtrace, and then quit gdb it isn't going to put anything into the text file. So from what it sounds you're not getting segfaults anymore.

**Comment by splace** [comment]
@JoshStrobl @tauchvogel seems to me some misunderstanding of each other. i am currently waiting on a segfault to report, usually 5+ hours.

**Comment by splace** [comment]
i notice, connected?, desktop-view, although being behind everything, is being drawn last, resulting in some nasty flashing when changing desktop.

**Comment by splace** [comment]
> i notice, connected?, desktop-view, although being behind everything, is being drawn last, resulting in some nasty flashing when changing desktop.

no, (its a bit fast to see) but its actually the previous desktop is not being un-drawn until after the new desktops windows and desktop-view have been drawn.

**Comment by splace** [comment]
@JoshStrobl the process as described did not work, gdb froze, so i started it without the piping and cut/pasted the output here. 

```
gdb us.getsol.budgie-desktop-view
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-solus-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from us.getsol.budgie-desktop-view...
Reading symbols from /usr/lib64/debug/.build-id/74/425d11e7979330f668d11fbaf8119fc95337d1.debug...
(gdb) r
Starting program: /usr/bin/us.getsol.budgie-desktop-view 
warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/home/simon/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/simon/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[New LWP 14027]
[New LWP 14028]
[New LWP 14029]

[Detaching after fork from child process 14067]
[New LWP 14069]
[New LWP 14070]
Initializing caja-xattr-tags extension
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
[LWP 14070 exited]
[LWP 14069 exited]
[Detaching after fork from child process 14097]
[New LWP 14099]
[New LWP 14100]
Initializing caja-xattr-tags extension
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
[LWP 14100 exited]
[LWP 14099 exited]
quit
[Detaching after fork from child process 14270]
[New LWP 14272]
[New LWP 14273]
Initializing caja-xattr-tags extension
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
[LWP 14273 exited]
[LWP 14272 exited]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "us.getsol.budgi" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d57090 in g_str_hash () from /usr/lib/libglib-2.0.so.0
(gdb) quit
A debugging session is active.

	Inferior 1 [process 14023] will be killed.

Quit anyway? (y or n) n
Not confirmed.
(gdb) backtrace full
#0  0x00007ffff7d57090 in g_str_hash () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff7d565d8 in g_hash_table_contains () at /usr/lib/libglib-2.0.so.0
#2  0x0000000000408a33 in desktop_view_on_mount_added
    (self=0x886380, mount=0xcf6280)
    at src/us.getsol.budgie-desktop-view.p/budgie_desktop_view.c:2720
        mount_uuid = 0x0
        _tmp0_ = 0x0
        _tmp1_ = 0x0
        _tmp2_ = <optimized out>
        _tmp3_ = 0x0
        _tmp4_ = <optimized out>
        __func__ = "desktop_view_on_mount_added"
#3  0x00007ffff7e590a2 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff7e6c8e4 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff7e776cf in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff7e78b0c in g_signal_emit_by_name ()
    at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff7e5c3ef in g_cclosure_marshal_VOID__OBJECTv ()
    at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7e592d6 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff7e77a54 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#10 0x00007ffff7e78b0c in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#11 0x00007fffe86506eb in  () at /usr/lib64/gio/modules/libgioremote-volume-monitor.so
#12 0x00007ffff7d6851e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff7d688d0 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7d6895f in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff7c18add in g_application_run () at /usr/lib/libgio-2.0.so.0
#16 0x0000000000406191 in budgie_desktop_view_app_main (args=0x7fffffffe758, args_length1=1) at src/us.getsol.budgie-desktop-view.p/application.c:116
        app = 0x4330f0
        _tmp0_ = 0x4330f0
        result = 0
#17 0x00007ffff727c0d3 in __libc_start_main () at /usr/lib/libc.so.6
#18 0x0000000000405f5e in _start () at ../sysdeps/x86_64/start.S:120
(gdb) 
```

**Comment by splace** [comment]
i tested mounting different removable media and found i always have the crash for my phone, EXCEPT when desktop is set to show active mounts?

my phone is using MTP (the default on android?) for which i have previously discovered some bugs, but since this works with desktop show mounts on, it doesn't seem to be related.

although in all cases it doesn't actually show any of those mounts except previously mounted ones?

with show mounts on adding/removing previously mounted drives (sata drives) work as expected (it shows them) but no usb connected mounts show, but since i never had mounts on desktop shown, i don't know if this has been the case previously.

**Comment by JoshStrobl** [comment]
Will see about reproducing this. Thanks for the backtrace :+1:

**Comment by JoshStrobl** [comment]
I was able to reproduce this issue and will work on a fix.
