### ISSUE TITLE
Cannot re-open minimized windows.

### ISSUE THREAD

**Issue by YehonatanV** [getsolus/budgie-desktop-view#12]
When minimizing a window to the panel, if it is the only un-minimized window in the workspace, it cannot be re-opened by clicking on its icon. You have to do e.g. Alt+Tab to show it again, or use it to focus on some other window, adter which you can again re-open it by clicking on its icon.

For example, if you have Firefox and Deadbeef open, and you minimize Firefox, you can click on it and refocus on it. But if you first minimize Deadbeef, then after minimizing Firefox it cannot be refocused when clicked upon.

(This is my first time using GitHub for any purpose, so if this needs rephrasing, please explain what is required and I'll edit accordingly.)

**Comment by JoshStrobl** [comment]
This isn't the Budgie Desktop issue tracker. Please submit your issue to https://github.com/solus-project/budgie-desktop. Thanks!
