### ISSUE TITLE
Opening desktop files in terminal issues

### ISSUE THREAD

**Issue by EbonJaeger** [getsolus/budgie-desktop-view#14]
While adding support for the Kitty terminal, I discovered some things about trying to open files in the other supported terminals:

- Alacritty crashes on start with: error: Found argument '--new-tab' which wasn't expected, or isn't valid in this context
- gnome-terminal displays this: 
![image](https://user-images.githubusercontent.com/5157277/102675628-22222780-4168-11eb-81d8-ecf72425d48b.png)
- konsole fails to open the file because it needs a command before the path (it thinks the path is a command, which fails)
- Tilix shows the same message as gnome-terminal

Mate terminal and Terminator fail to open, but that's due to issues not related to budgie-desktop-view.

The question I'd ask is: is it desirable to support the feature of opening files in a terminal? Each terminal appears to have its own challenges; Nautilus also doesn't have this ability. The `-e` option is deprecated in gnome-terminal (though how much that actually means is anyone's guess), though it does look like there's a different syntax to run a command after opening, presuming we can choose an editor to open the file with.

EDIT: As an additional note, I'm using the Fish shell. I wonder if using stock Bash changed things. Will test in the morning.

**Comment by kovidgoyal** [comment]
You can specify the command to run directy in kitty like this

kitty vim whatever.txt

and for compatibility with other terminals you can even stick an -e in there that kitty will ignore.

**Comment by EbonJaeger** [comment]
I swear I tried that... ugh. Edited.

**Comment by kovidgoyal** [comment]
You would typically use the $VISUAL and $EDITOR environment variables to decide the editor.  For image files, at least with kitty, you can do

kitty kitty +kitten icat --hold whatever.jpeg

No clue what you would do with other terminals.

**Comment by kovidgoyal** [comment]
Or if you want to open the image in terminal and have a shell after display the image:

kitty sh -c "kitty +kitten icat file.jpeg; $SHELL"

replace $SHELL witht eh shell you get from /etc/passwd or the SHELL env var.

**Comment by EbonJaeger** [comment]
Thanks to @kovidgoyal 's hints above, I have opening text files in a terminal editor working now! Thanks for that! :)

I guess that just leaves the decision as to how to handle other types of files.

**Comment by EbonJaeger** [comment]
I think this can be considered closed now. :D
