### ISSUE TITLE
dekstop icons open with Visual studio code.

### ISSUE THREAD

**Issue by kp2401075** [getsolus/budgie-desktop-view#18]
System Info:
Hardware: Thinkpad 470s
OS : Solus-Budge : latest updates installed.

Issue:
When I try opening home folder / trash it opens with Visual studio code.

When did it start:
 since the introduction of budgie-desktop-view

Here is a video recording showing the issue.
https://youtu.be/HmUrxF0-RBQ

Please let me know if more info is required to troubleshoot.

**Comment by JoshStrobl** [comment]
This isn't an issue with Budgie Desktop View. Please make sure you have a correct inode/directory handler in your `.config/mimeapps.list`

**Comment by kp2401075** [comment]
Thanks just got it fixed. :smile:
