### ISSUE TITLE
Not working in Arch

### ISSUE THREAD

**Issue by TheGamingCoderNoob** [getsolus/budgie-desktop-view#19]
Is there anything I'm missing? I rtried building it using meson and now what do I do? Cause it does not work.

**Comment by JoshStrobl** [comment]
Unless you're able to provide some logs from running the process after installation, I cannot possibly know why it is "not working" for you under Arch. Our README provides clear information on building and installation, our wiki has a document on providing backtraces should you have a segfault.

As you have provided no details, closing as invalid. Feel free to follow-up with details.
