### ISSUE TITLE
Ability to launch shell scripts

### ISSUE THREAD

**Issue by JacekJagosz** [getsolus/budgie-desktop-view#20]
Right now we can launch apps through a .desktop file, but we can't launch a shell script from the desktop. Even though it is set as an executable it just opens in text editor. 
I would love if possibility that feature could be implemented. It is also worth thinking about if when you click it should it execute or open in editor (I think the 1st option), and if there should be additional options when you right click, like "Execute", "Execute in terminal" apart from "Open" and "Open in terminal".

**Comment by DataDrake** [comment]
If it were to be implemented, I think it would make sense for it to be implicitly executed in a terminal, like when you're running a `.bat` file on Windows. If you wanted to start something that would run in the background, or spawn without a shell, making a `.desktop` file makes more sense to me.

In any case, you can at least work around this right now by authoring a `.desktop` file and setting the `Terminal` key accordingly.

**Comment by JoshStrobl** [comment]
You can launch a shell script from the desktop, however it is entirely up to the Terminal of your choice on whether or not it keeps the process open, closes the Terminal on its closure, or prevents further input after it exits. Open in Terminal is effectively the same as "execution".

A Desktop file is the best option generally speaking.
