### ISSUE TITLE
not all files shown + blank area on right.

### ISSUE THREAD

**Issue by splace** [getsolus/budgie-desktop-view#21]
![Screenshot from 2021-02-26 02:51:40](https://user-images.githubusercontent.com/1234848/109248411-a8e52780-77dd-11eb-8c09-31c36127b526.png)

**Comment by JoshStrobl** [comment]
This is calculated based on screen resolution, icon sizing, etc. It's a guesstimate at best. More details like your screen resolution are needed.

**Comment by splace** [comment]
would generally want to be able to change resolution and icon size as-and-when, so i guess project not for me.

**Comment by JoshStrobl** [comment]
Yes? That's the point. I'm trying to ascertain what your resolution is so I can determine if there is better calculation that needs to happen..

But okay :+1:
