### ISSUE TITLE
Desktop View Not Working In Solus

### ISSUE THREAD

**Issue by NickJ2911** [getsolus/budgie-desktop-view#9]
I was talking with JoshStrobl on the Solus forum and he suggested I follow up on here to resolve this issue.

 Just ran: us.getsol.budgie-desktop-view in terminal and got back: Segmentation fault (core dumped)

I'm new to linux and solus so you might have to simplify the trouble shooting a little. Thanks!

**Comment by JoshStrobl** [comment]
This is a duplicate of #6.
